let data = {
    "success": [
        {
            "data": [
                {
                    "id": "lsipyl5s",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": "null",
                    "question": "<p>python code to get all keywords list</p>",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "<p>from keywords import kwlist</p>",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "<p>from keyword import kwlist</p>",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "<p>from keywords import keywordlist</p>",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "<p>from keyword import keywordlist</p>",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "<p>NA</p>",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:16:27.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5t",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "Which of the following is used for comments in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "// This is a comment",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "/* This is a comment */",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "# This is a comment",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "<!-- This is a comment -->",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5u",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "Which function is used to take user input in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "input()",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "get_input()",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "user_input()",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "read_input()",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5v",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "What does the `%` operator do in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Exponentiation",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Modulo",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Floor division",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Bitwise AND",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5w",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "Which data type is used to store a sequence of characters in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "int",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "float",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "str",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "bool",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5x",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "What is the purpose of the `len()` function in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "To calculate logarithms",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "To find the length of a string or list",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "To convert to lowercase",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "To generate random numbers",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5y",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "What is the correct way to declare a variable in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "variable = 5",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "5 = variable",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "variable : 5",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "5 : variable",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl5z",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": "null",
                    "question": "<p>What is the output of the following code snippet? <br />&gt;&gt;&gt; x = 5 <br />&gt;&gt;&gt; y = 2 <br />&gt;&gt;&gt; result = x / y <br />&gt;&gt;&gt; print(result)</p>",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "<p>2.5</p>",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "<p>2</p>",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "<p>2</p>",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "<p>2.25</p>",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "<p>NA</p>",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:17:22.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl60",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "Which operator is used for string concatenation in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "+",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "*",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "/",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "%",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl61",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "How do you check if a key is present in a dictionary?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "key in dictionary",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "dictionary[key]",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "dictionary.contains(key)",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "contains(key, dictionary)",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl62",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "What does the `ord('A')` function return in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "65",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "'A'",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "1",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "0",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl63",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "Which of the following is a valid way to open a file in Python for reading?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "file = open(\"example.txt\", \"r\")",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "file = open(\"example.txt\", \"w\")",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "file = open(\"example.txt\", \"a\")",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "file = open(\"example.txt\", \"rw\")",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl64",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "What is the purpose of the `str()` function in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "To convert a string to lowercase",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "To concatenate strings",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "To convert a number to a string",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "To convert a any object to a string object",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl65",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "What is the result of the expression `-2**3**2` in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "512",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "-512",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "-16",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "16",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsipyl66",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Easy",
                    "reference": null,
                    "question": "Which of the following is a boolean operator in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "nd",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "or",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "not",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "All of the above",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:15:46.000Z",
                    "updated_at": "2024-02-12T09:15:46.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lm9",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "In the print statement, brackets () are optional only when using Python 2.x. ?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "correct statement",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "incorrect statement",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Invalid statement",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "None of the above",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lma",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": ">>> print(\"Hello\");",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Here semicolon ( ; ) is manditory",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Here semicolon ( ; ) is optional",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "None of the above",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Invalid syntax",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmb",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "Which of the following is wrong ?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "; is optional in python",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "pass; is a valid code",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": ">>>; through error once enter key is pressed",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "we can't use ; in python",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmc",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "why was guido van Rossum named python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Big long python snake is popular during 1991, Hence named as python",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Python is named because python can be written as Py(pie) + th(Theta) + on (Omega). As it is widely used in scientific research",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "python named TV show",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "guido van Rossum's daughter's toy name was python. Hence named python",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmd",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "Python is a high-level language. Whereas what does mean by high-level-languages?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "As python is also used in English Literature, Hence it is called as high-level language",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "The high-level language is easy to read, write and maintain as it is written in English-like words",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "It sits on top of other languages, Hence it is called height-level language",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "It acts as a balance between humans and computers, Hence it is called as high-level-language",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lme",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "How will you do the square root of a number (n) in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "sq_root = n ** 0.5",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "sq_root = square_root(n)",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "sq_root = n.sqrt()",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "sq_root = maths.square_root(n)",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmf",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "Output of ord(65)",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "A",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "a",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "65",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Type Error",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmg",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "Compute => 10 % -2 ** 2",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "2.5",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "-2",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "-25",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "-2.5",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmh",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "which of the following is valid code",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "True = 10 + 10",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "True = 10 + 001",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "true = 10 + 10",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "true = 10 + 001",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmi",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": ">>> 3 + 4j * 6j",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "-21",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "(-21 + 0j)",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "27",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "(27 + 0j)",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmj",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "2 * 3 ** 4",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "162",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "1296",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "24",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "None of the above",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmk",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": ">>> 22 % 5",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "-3",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "3",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "2",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "-2",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lml",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "print in 3.x",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "keyword",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "library function",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "user defined function",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "both keyword and function",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmm",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": ">>> print(print('hai',end=\"\"))",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "hai",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "`None`",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "haiNone",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "NoneNone",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiq6lmn",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "Medium",
                    "reference": null,
                    "question": "default value of sep in print function is",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "' ' - a single space",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "'' - an empty string",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "'\\n' - a new line",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "None - None value",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T09:22:00.000Z",
                    "updated_at": "2024-02-12T09:22:00.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoc",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "Python modulus operator ( % ), result sign is ?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "same as \"denominator\"",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "same as \"numerator\"",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "opposite as \"denominator\"",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "opposite as \"numerator\"",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqod",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "What is the output of the expression (-17) % 3 in Python?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "-2",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "2",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "-1",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "1",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoe",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "In Python 2.x, what is the value of 11/3?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "4",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "3.66666666666665",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "3",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "3.66666666666",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqof",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "In the expression `5%3/2*100//1`, list the operators in execution order based on the priority table.",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "/, *, //, %",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "%, /, //, *",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "/, %, //, *",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "%, /, *, //",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqog",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "Which operator has the least priority in Python ?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Addition",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "multiplication",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "exponentiation",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "assignment",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoh",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "Which operator has the second most priority?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Addition",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "multiplication",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "exponentiation",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "assignment",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoi",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "In the expression `(2-4)**2*4/2`, which operator gets executed first and which operator gets executed last?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "First: -, Last: /",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "First: **, Last: *",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "First: **, Last: /",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "First: -, Last: *",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoj",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "Why does `-5%2` result in 1 instead of -1 ?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Python bug",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Modulus operation always returns positive values",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Implementation-specific behavior",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Undefined behavior",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqok",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "What are all the operators that follow the R->L execution order?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "+, -, *, /",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "=, **, %",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "**, /, %",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "=, **",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqol",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "In the expression `2**3**2`, what is the output, and how can you represent this in mathematics?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Output: 64; Representation: 2^(3^2)",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Output: 512; Representation: (2^3)^2",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Output: 64; Representation: (2^3)^2",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Output: 512; Representation: 2^(3^2)",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqom",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "Explain why `22//-7` is -4?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Floor division rounds towards zero",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Floor division always rounds down",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Division by a negative number results in a negative quotient",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "It's a Python bug",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqon",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "What is the output for `0/0` in python? And do we get the same output in all other programming languages?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Output: 0; Yes",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Output: 0; No",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Output: ZeroDivisionError; No",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Output: NaN; Yes",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_3",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoo",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "What is the output of `a///b` where a = 4 and b = 2",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "2",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "4",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "1",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Error",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_4",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqop",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "In the expression `-4**-0.5`, what is the output, and why?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Output: -0.5; Exponentiation is performed before negation",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Output: 0.5; Negative exponent results in a fraction",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Output: -2; Exponentiation is performed before negation",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Output: 2; Exponentiation is performed before negation",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_1",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                },
                {
                    "id": "lsiykqoq",
                    "chapter_id": "lsilx1vq",
                    "paragraph_id": null,
                    "type": "single_option",
                    "difficulty": "difficulty",
                    "reference": null,
                    "question": "In the expression `marvel = ironman = loveu3000 = 3000`, is the above code valid or not?",
                    "question_image": null,
                    "num_options": 0,
                    "option_1": "Invalid; multiple assignments on a single line are not allowed",
                    "option_1_image": null,
                    "option_1_partial": null,
                    "option_2": "Valid",
                    "option_2_image": null,
                    "option_2_partial": null,
                    "option_3": "Invalid; variable names cannot start with a number",
                    "option_3_image": null,
                    "option_3_partial": null,
                    "option_4": "Valid; but assigns different values to each variable",
                    "option_4_image": null,
                    "option_4_partial": null,
                    "option_5": null,
                    "option_5_image": null,
                    "option_5_partial": null,
                    "correct": "option_2",
                    "explanation": "NA",
                    "explanation_image": null,
                    "user_id": "lp8ndo2k",
                    "user_role": "vendors",
                    "verified_by": null,
                    "verify_role": null,
                    "verified": 0,
                    "verified_difficulty": null,
                    "created_at": "2024-02-12T13:16:57.000Z",
                    "updated_at": "2024-02-12T13:16:57.000Z",
                    "chapter": "Basics of Python",
                    "module_id": "lsfzw2jc",
                    "module": "Weekly Python 01 - Foundations of Python"
                }
            ],
            "msg": "Action Performed"
        }
    ]
}

let idx = process.argv[2]
qn = data.success[0].data[idx]

console.log("total question: ", data.success[0].data.length)
let question = qn.question;
options = [1, 2, 3, 4].map(x => {
    return qn['option_' + x]
})
console.log("--------------------------------------------");
console.log(`QN : ${parseInt(idx) + 1}`, question);
console.log("---------------")
options.forEach((x, id) => {
    console.log((id + 1) + ") " + x);
})
console.log("--------------------------------------------");
